### PR TITLE
Optional custom author in each article

### PR DESCRIPTION
**Pull request by anzai249**
#243 
Preview:

image

image

You should add these to your front-matter if you want to custom the author of this article:

```
author:
  name: "Author Name"
  avatar: "Author Avatar"
  label: "Author Label, Lv1, Lv2 or so."
```

### CODE REVIEW

**Comment by anzai249** [comment]
If the article is written by yourself (the author in config.yml), you can just leave it blank.

```
author:
  name: 
  avatar: 
  label: 
```

**Comment by anzai249** [comment]
NO 2

fixed this bug:

Before:

image

After:

image

**Comment by shawn0915** [comment]
> ```
> author:
>   name: 
>   avatar: 
>   label: 
> ```

可是这样就不兼容之前的设定了，也许改成这样比较好？

```
author:
author_avatar: 
author_label: 
```

**Comment by EvanNotFound** [comment]
已在 Commit 15d370cdb257c061a97de30396927e5180145ae1 添加支持，感谢 PR

**Pull request closed without merging**
