### PR TITLE
Update zh-CN translate and 404 page style(a little)

### PR DESCRIPTION
**Pull request by FrederickBun**
## Summary by CodeRabbit

- **New Features**
  - Added new translations for "status" and other terms in multiple languages (Japanese, Simplified Chinese, Traditional Chinese).

- **Updates**
  - Updated the translation strings for the table of contents and search functionality in multiple languages.
  - Improved the clarity of post count messages and article timestamps in Simplified Chinese.

- **Bug Fixes**
  - Corrected minor translation issues in Traditional Chinese.

- **Style**
  - Updated the 404 page template to improve readability.

### CODE REVIEW

**Comment by EvanNotFound** [comment]
@coderabbitai

**Comment by EvanNotFound** [comment]
@coderabbitai review

**Comment by EvanNotFound** [comment]
status 在 `ja` `zh-CN` `zh-TW` 中重复了，导致 build 出现错误，请修复

**Comment by FrederickBun** [comment]
好的

**Comment by FrederickBun** [comment]
@EvanNotFound 已经修复

**Comment by FrederickBun** [comment]
@coderabbitai review

**Pull request merged**
